#!/usr/bin/env bash

# Create Script
# This script creates a new bash script, sets permissions and more
# Author: Jordan


if [[ ! $1 ]]; then
    echo "Missing arguement"
    exit 1
fi

scriptname="$1"
bindir="${HOME}/bin"
filename="${bindir}/${scriptname}"


if [[ -e $filename ]]; then
    echo "File ${filename} already exists"
    
    exit 1
fi

if type "$scriptname"; then
    echo "There is already a command with name ${scriptname}"
    exit 1
fi

if [[ ! -d $bindir ]]; then
    
    if mkdir "$bindir"; then
        echo "created ${bindir}"
    else
        echo "Could not create ${bindir}"
        exit 1
    fi
fi

echo '#!/bin/bash' > "$filename"

chmod u+x $filename

if [[ $EDITOR ]]; then
    $EDITOR "$filename"
else
    echo "Script created; \$EDITOR not set"
fi
