#!/bin/bash



date=$(date)

topic="$1"

filename="${HOME}/notes/${topic}notes.txt"

read -p "Note: " note

if [[ $note ]]; then
    echo "$date: $note" >> "$filename"
    echo "Note '$note' saved to $filename"
else
    echo "No input. note not saved"
fi

